// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfNWDL70pgmzPkuzbRvZF_eGZY0pSubAE',
    appId: '1:1062133734223:web:5f77a393a3394d8226433a',
    messagingSenderId: '1062133734223',
    projectId: 'world-news-c4b40',
    authDomain: 'world-news-c4b40.firebaseapp.com',
    storageBucket: 'world-news-c4b40.appspot.com',
    measurementId: 'G-JZWP49E0VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXFPYianjI1sz8FPRcxX8NWdTePzUOLHo',
    appId: '1:1062133734223:android:c2562f83c8b8c55826433a',
    messagingSenderId: '1062133734223',
    projectId: 'world-news-c4b40',
    storageBucket: 'world-news-c4b40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE001WEqt6Z3WWV60rEUJgsXaRIhxOet0',
    appId: '1:1062133734223:ios:1519657072ccbe6c26433a',
    messagingSenderId: '1062133734223',
    projectId: 'world-news-c4b40',
    storageBucket: 'world-news-c4b40.appspot.com',
    iosClientId: '1062133734223-bl30jkbagg7iqcnf78b0ds7k168vovdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.uworldNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE001WEqt6Z3WWV60rEUJgsXaRIhxOet0',
    appId: '1:1062133734223:ios:1519657072ccbe6c26433a',
    messagingSenderId: '1062133734223',
    projectId: 'world-news-c4b40',
    storageBucket: 'world-news-c4b40.appspot.com',
    iosClientId: '1062133734223-bl30jkbagg7iqcnf78b0ds7k168vovdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.uworldNews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfNWDL70pgmzPkuzbRvZF_eGZY0pSubAE',
    appId: '1:1062133734223:web:bbdd98006fc4031526433a',
    messagingSenderId: '1062133734223',
    projectId: 'world-news-c4b40',
    authDomain: 'world-news-c4b40.firebaseapp.com',
    storageBucket: 'world-news-c4b40.appspot.com',
    measurementId: 'G-2YKXR18H0F',
  );
}
